- name: Check if kubernetes installation exists
  stat:
    path: "/etc/kubernetes/pki"
  register: result

- name: Initialize the cluster using kubeadm
  ansible.builtin.command: kubeadm init --apiserver-advertise-address="192.168.56.10" --apiserver-cert-extra-sans="192.168.56.10" --pod-network-cidr=10.10.42.0/16
  when: not result.stat.exists

- name: Create kube config directory
  ansible.builtin.file:
    path: /home/vagrant/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf to user's kube config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: yes
    owner: vagrant

- name: Install Pod network (Weave)
  ansible.builtin.command: "kubectl --kubeconfig=/home/vagrant/.kube/config apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml"
    
- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"