# - name: Install containerd
#   ansible.builtin.apt:
#     name: containerd
#     state: present
#     update_cache: yes

# - name: Create containerd config directory
#   ansible.builtin.file:
#     path: /etc/containerd
#     state: directory
#     mode: '0755'

# - name: Generate default config
#   ansible.builtin.shell: |
#     containerd config default | tee /etc/containerd/config.toml

- name: Install packages that allow apt to be used over HTTPS
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Create directory for Docker’s official GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    recurse: true
    mode: '0755'

# - name: Add Docker’s official GPG key
#   ansible.builtin.command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# - name: Add Docker GPG key
#   apt_key:
#     url: https://download.docker.com/linux/ubuntu/gpg

# - name: Add Docker GPG key
#   ansible.builtin.get_url:
#     url: https://download.docker.com/linux/ubuntu/gpg
#     dest: /etc/apt/keyrings/docker.gpg
#     mode: '0644'
#     force: true

- name: Check if docker.gpg exists
  stat:
    path: "/etc/apt/keyrings/docker.gpg"
  register: result

- name: Add Docker GPG key
  ansible.builtin.shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  when: not result.stat.exists

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable
    state: present
    filename: /etc/apt/sources.list.d/docker

- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present
    update_cache: yes

- name: Remove config.toml
  ansible.builtin.file:
    path: /etc/containerd/config.toml
    state: absent

- name: Generate default config
  ansible.builtin.shell: |
    containerd config default | tee /etc/containerd/config.toml

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
